name: ensemblify_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astunparse=1.6.3
  - biopython=1.84
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - c-blosc2=2.15.1
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.7.4
  - cftime=1.6.4
  - colorama=0.4.6
  - contact_map=0.7.0
  - contourpy=1.2.1
  - cycler=0.12.1
  - fasteners=0.17.3
  - fonttools=4.53.1
  - freetype=2.12.1
  - future=1.0.0
  - griddataformats=1.0.2
  - gsd=3.3.1
  - h5py=3.11.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=75.1
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.9.1
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib-base=3.9.2
  - mda-xdrlib=0.2.0
  - mdanalysis=2.7.0
  - mdtraj=1.10.0
  - mmtf-python=1.1.3
  - mrcfile=1.5.3
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf4=1.7.1
  - networkx=3.3
  - nomkl=1.0
  - numexpr=2.10.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - patsy=0.5.6
  - pillow=10.4.0
  - pip=24.2
  - plotly=5.23.0
  - pthread-stubs=0.4
  - py-cpuinfo=9.0.0
  - pyedr=0.8.0
  - pyparsing=3.1.4
  - pytables=3.10.1
  - python=3.10.13
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytng=0.3.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=72.2.0
  - six=1.16.0
  - snappy=1.2.1
  - statsmodels=0.14.2
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tidynamics=1.1.2
  - tk=8.6.13
  - tqdm=4.66.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.3.1
  - zlib-ng=2.2.1
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - cachetools==5.5.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorful==0.5.6
      - distlib==0.3.8
      - filelock==3.15.4
      - frozenlist==1.4.1
      - google-api-core==2.19.2
      - google-auth==2.34.0
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.0
      - idna==3.8
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - linkify-it-py==2.0.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdit-py-plugins==0.4.1
      - mdurl==0.1.2
      - memray==1.13.4
      - multidict==6.0.5
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - prometheus-client==0.20.0
      - proto-plus==1.24.0
      - protobuf==5.27.4
      - py-spy==0.3.14
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.18.0
      - ray==2.35.0
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.8.0
      - rpds-py==0.20.0
      - rsa==4.9
      - smart-open==7.0.4
      - textual==0.78.0
      - uc-micro-py==1.0.3
      - urllib3==2.2.2
      - virtualenv==20.26.3
      - wrapt==1.16.0
      - yarl==1.9.4
