name: ensemblify_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astunparse=1.6.3
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.2
  - c-blosc2=2.15.1
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cftime=1.6.4
  - colorama=0.4.6
  - contourpy=1.3.0
  - cycler=0.12.1
  - fasteners=0.17.3
  - fonttools=4.54.1
  - freetype=2.12.1
  - gflags=2.2.2
  - glog=0.7.1
  - griddataformats=1.0.2
  - gsd=3.4.1
  - h5py=3.12.1
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=75.1
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=13.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnl=3.10.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzip=1.11.1
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib-base=3.9.2
  - mda-xdrlib=0.2.0
  - mdanalysis=2.6.1
  - mdtraj=1.9.9
  - mmtf-python=1.1.3
  - mrcfile=1.5.3
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf4=1.7.1
  - networkx=3.4.2
  - nomkl=1.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - patsy=0.5.6
  - pillow=11.0.0
  - pip=24.3.1
  - pthread-stubs=0.4
  - py-cpuinfo=9.0.0
  - pyarrow=13.0.0
  - pyedr=0.8.0
  - pyparsing=3.2.0
  - pytables=3.10.1
  - python=3.10.15
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytng=0.3.3
  - pytz=2024.2
  - qhull=2020.2
  - rdma-core=54.0
  - re2=2023.09.01
  - readline=8.2
  - s2n=1.4.17
  - scikit-learn=1.4.2
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - statsmodels=0.14.4
  - threadpoolctl=3.5.0
  - tidynamics=1.1.2
  - tk=8.6.13
  - tqdm=4.66.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ucx=1.16.0
  - unicodedata2=15.1.0
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - zlib=1.3.1
  - zlib-ng=2.2.2
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - billiard==4.2.1
      - biopython==1.81
      - bleach==6.1.0
      - blosc==1.11.2
      - cachetools==5.5.0
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorful==0.5.6
      - dask==2024.10.0
      - dask-jobqueue==0.9.0
      - defusedxml==0.7.1
      - distlib==0.3.9
      - distributed==2024.10.0
      - ensemblify==1.0.0
      - fastjsonschema==2.20.0
      - filelock==3.16.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.22.0
      - google-auth==2.35.0
      - googleapis-common-protos==1.65.0
      - grpcio==1.67.1
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.10
      - importlib-metadata==8.5.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - linkify-it-py==2.0.3
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - memray==1.14.0
      - mistune==3.0.2
      - multidict==6.1.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - partd==1.4.2
      - plotly==5.19.0
      - prometheus-client==0.21.0
      - propcache==0.2.0
      - proto-plus==1.25.0
      - protobuf==5.28.3
      - psutil==6.1.0
      - py-spy==0.3.14
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pyrosetta==2024.42+release.3366cf78a3
      - pyrosetta-distributed==0.0.3
      - pyrosetta-installer==0.1.2
      - python-json-logger==2.0.7
      - python-xz==0.5.0
      - pyyaml==6.0.1
      - pyzmq==26.2.0
      - ray==2.33.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.3
      - rpds-py==0.20.0
      - rsa==4.9
      - send2trash==1.8.3
      - smart-open==7.0.5
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - tblib==3.0.0
      - tenacity==9.0.0
      - terminado==0.18.1
      - textual==0.85.1
      - tinycss2==1.4.0
      - tomli==2.0.2
      - toolz==1.0.0
      - types-python-dateutil==2.9.0.20241003
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - urllib3==2.2.3
      - virtualenv==20.27.1
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - yarl==1.17.0
      - zict==3.0.0
      - zipp==3.20.2
